challenge:
    resource: "@ChallengeBundle/Resources/config/routing.yml"
    prefix:   /challenge

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix:   /mission

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
my:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
